### ISSUE TITLE
Icon for english still shown after the language is switched to x

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin.net#130]
It should change the icon to the language the page is loaded with.

![image](https://user-images.githubusercontent.com/7818961/72057049-0c588100-32ce-11ea-8fa8-cb31b9999bf8.png)

![image](https://user-images.githubusercontent.com/7818961/72057077-15e1e900-32ce-11ea-9468-bd5de00fb5a2.png)

**Comment by peerchemist** [comment]
Also bug with Portuguese as you can see.

**Comment by captainbuckkets** [comment]
Addressed in https://github.com/peercoin/peercoin.net/pull/131

**Comment by peerchemist** [comment]
@kazzkiq reminder

**Comment by peerchemist** [comment]
Clicking on the Korean icon does nothing.
