### ISSUE TITLE
New page: Contribute

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin.net#133]
Under Project -> Contribute

_________________________________

## Contribute — How You Can Help Make Peercoin Better

Peercoin is a free/open-source project, and you are more than welcome to help us make it better! There are many ways you can help:

### Reporting Bugs

If you find bugs in Peercoin client, we need you to file them in our issue tracker. Your problem may have already been reported, so it’s a good idea to check to avoid filing a duplicate. Learn more about [link to github here]

Suggestions for new features and enhancement requests [link to github here]

### Help Others With Their Bug Reports

You can help the development team keep up with the bug reports by closing duplicates, helping to clarify reporters problems, and confirming that you can reproduce bugs. Learn more about [link here]

### Translate Peercoin Into Your Language

Peercoin has been translated into dozens of languages, but if the translation for your language doesn’t exist or is out of date, you can help bring Peercoin to entire new populations simply by translating some text. Learn [link here]

### Write Code

We welcome code contributions from anyone, whether you have a one-line fix or a big idea, a lot of experience programming or none at all. Learn more about [link here]

**Comment by peerchemist** [comment]
@bananenwilly while you are at it can you also do this?

**Comment by bananenwilly** [comment]
For this page to look more streamlined with the rest of peercoin.net, I changed the inline links to buttons. 

I need links for 

- Help Others
- Translate
- Write Code

https://peercoinnet-git-contribute.peercoin.vercel.app/contribute

**Comment by peerchemist** [comment]
Help others - forums or discord
Translate - transifex
Write Code - Github
