### ISSUE TITLE
Where's the repo for trezor-api compatible blockbook.peercoin.net?

### ISSUE THREAD

**Issue by greatwolf** [peercoin/peercoin.net#158]
In addition to title, it appears blockbook.peercoin.net does not currently support all of the trezor api endpoints. In particular, `/api/xpub/<xpub>` does not work. [See for reference](https://github.com/trezor/blockbook/blob/master/docs/api.md#get-xpub).

**Comment by backpacker69** [comment]
https://github.com/backpacker69/blockbook/commits/peercoin

xpub is not supported, as peercoin version is based on much older version of blockbook

**Comment by belovachap** [comment]
Oh cool, I didn't know people are trying to use the api. Just curious, @greatwolf what are you trying to do with it?

**Comment by greatwolf** [comment]
I'm looking at the viability of implementing peercoin support into my KeepKey Client fork. I still have to get KeepKey firmware maintainers to accept a PR that adds peercoin in there. It's literally a one line addition. That's an issue I'll have to take up with them.

Anyway, having `/api/xpub` is important since having to fallback to `/api/address` endpoint would mean making numerous multiple REST request depending on how many addresses are used for a given `xpub`. With `/api/xpub` the number of REST calls can be greatly condensed. I also looked at insight's api, which supports bulk address request but that api's from an older deprecated insight. Blockbook does not seem to have anything similar to that for addresses which leaves only `/api/xpub` endpoint.

**Comment by greatwolf** [comment]
I take it there's no real interest in adding Peercoin support to KeepKey? The only requirement I have is that peercoin's blockbook hosted at https://blockbook.peercoin.net/ be updated to something more recent so `/api/xpub` and `/api/utxo` are available. I can take care of the rest.

**Comment by peerchemist** [comment]
Well open a ticket on the blockbook repository (our fork). This is about the web site itself. I don't think keep key has many user but this looks quite doable. We can put it on the roadmap for this year.

**Comment by greatwolf** [comment]
Do you mean https://github.com/backpacker69/blockbook/tree/peercoin? The issues tab seems to be disabled since it's not visible.

**Comment by greatwolf** [comment]
Just wondering has this been added to the roadmap?

**Comment by peerchemist** [comment]
Yes, but due to more pressing issues at the moment it's gonna wait for a bit while longer.

**Comment by greatwolf** [comment]
What's the status of this? I hope this hasn't been completely forgotten..
