### ISSUE TITLE
Replace Header Content with New SVG File

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin.net#247]
For the home page header, I want to remove the leaf svg, the pioneer of proof of stake title, and the slogan text and replace all 3 with one svg that includes the logos and slogan together. That svg can be found in the following file path of the 2021 logo package...

Vertical Set > With Slogan > Outside Circle > White Leaf - White Text > peercoin-vertical-whiteleaf-whitetext-transparent_slogan.svg

This would also require replacing everything on the various translated pages as well. The new slogan has never been officially translated anyway, so all the translations of the slogan are outdated. For now we can just use the same English svg on all the different translations. We can fix this later on once the website gets redesigned.

This is how it currently looks...

![photo_2021-06-13_13-30-58](https://user-images.githubusercontent.com/5800997/121990579-fde88180-cd6b-11eb-9a91-13b3dff77404.jpg)

This is how it should look after fixing...

![photo_2021-06-13_13-23-52](https://user-images.githubusercontent.com/5800997/121990631-12c51500-cd6c-11eb-8e48-abc8c4cf3ecd.png)

**Comment by bananenwilly** [comment]
closed with https://github.com/peercoin/peercoin.net/pull/252
