### ISSUE TITLE
New section of peercoin.net: /resources

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin.net#296]
To be placed under #exchanges. A new heading that says Wrapped Peercoin. Then under the heading, you have a short description of wPPC with a link to the bridge website. Then under that, you would have the normal block links to Uniswap and QuickSwap.

**Comment by Sentinelrv** [comment]
Description text...

Wrapped Peercoin (wPPC) is a synthetic Peercoin-backed token. wPPC is created when peercoin is wrapped using bridge.peercoin.net and destroyed as peercoins are unwrapped.

Also, each block says "exchange" under the logo of the exchange. I think we should also add the network the exchange is hosted on. So it would say "Ethereum Exchange"  under the Uniswap logo and "Polygon Exchange" under the QuickSwap logo. I imagine this would make it easier for users to tell them apart. Does this make sense to add?
