### ISSUE TITLE
Trim Peercoin Primer Text

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin.net#330]
In the Peercoin Primer section of the home page, the text used there is too long and unnecessary. This text...

"The Peercoin Primer is a short five part video series covering the basic fundamentals of Peercoin. Learn about important topics such as Peercoin's initial distribution, how Proof-of-Stake consensus works and the many benefits it offers, Peercoin's economic model and its use of limited inflation to produce sustainable security. Finally, we'll explain Peercoin's long-term mission as a trustless backbone cryptocurrency."

Please trim off all the text except for the first sentence here...

"The Peercoin Primer is a short five part video series covering the basic fundamentals of Peercoin."

**Comment by selfwithin** [comment]
Keep the word "Proof Of stake" consensus.

**Comment by selfwithin** [comment]
"The Peercoin Primer is a short five part video series covering the basic fundamentals of Peercoin and how Proof-of-Stake consensus works."

**Comment by willyfromtheblock** [comment]
this is identical with https://github.com/peercoin/peercoin.net/pull/327/files?
which is already live on peercoin.net

**Comment by Sentinelrv** [comment]
Alright scratch this then. I didn't realize Peerchemist already made the change.
