### ISSUE TITLE
Black Menu Text Over Green Backround

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin.net#77]
When I open the main menu and scroll over items in a dropdown menu, the background is supposed to turn from white to green and the icons and titles are supposed to turn white. However when the transition happens there is a split second where the title text is black on top of a green background. It happens quickly, but it is noticeable. I've included a screenshot below...

<img width="228" alt="menublack" src="https://user-images.githubusercontent.com/5800997/52510842-a817d380-2bcb-11e9-9444-b63f2f27b071.png">

**Comment by captainbuckkets** [comment]
What browser?
