### ISSUE TITLE
Have shasums.txt file in the repo

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin.net#93]
A file which would contain the variables (sha256 sums) for each of the builds (linux, osx, windows).
From this file each of the translated pages can read the sum.

This would save a lot of time during the updates.

**Comment by kazzkiq** [comment]
Now wallet data is located at [`wallet.json`](https://github.com/peercoin/peercoin.net/blob/master/public/data/wallets.json) and can be easily updated for all three platforms (including binary links).

JSON example:

```json
{
  "os": "Linux",
  "img": "/img/icons/linux.png",
  "checksum": "4f70268af74bb83acf0350c61ae1ce43fc3c03f831d5c4fd75624717e5dce316",
  "link": "https://github.com/peercoin/peercoin/releases/download/v0.8.4ppc/peercoin-0.8.4-x86_64-linux-gnu.tar.gz"
}
```
